# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-graph2
networks:
- id: 137
  start_block: ${ENVIO_START_BLOCK}
  contracts:
  - name: ERC1967Proxy
    address:
      - ${ENVIO_CONTRACT_ADDRESS}
    handler: src/EventHandlers.ts
    events:
    - event: DataGroupConsensusUpdated(bytes32 indexed dataGroupHash, uint256 oldValue, uint256 newValue)
    - event: DataGroupHeartBeat(bytes32 indexed propertyHash, bytes32 indexed dataGroupHash, bytes32 indexed dataHash, address submitter)
    - event: DataSubmitted(bytes32 indexed propertyHash, bytes32 indexed dataGroupHash, address indexed submitter, bytes32 dataHash)
    - event: Initialized(uint64 version)
    - event: MinimumConsensusUpdated(uint256 oldValue, uint256 newValue)
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
    - event: Upgraded(address indexed implementation)
unordered_multichain_mode: true
preload_handlers: true
